language: rust
rust:
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
sudo: true
before_install:
  - sudo add-apt-repository -y "ppa:marutter/c2d4u"
  - sudo apt-get update
  - sudo apt-get install -y --no-install-recommends openssl
